name: Test Suite

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    strategy:
      matrix:
        elixir: ['1.8', '1.9', '1.10']

    runs-on: ubuntu-latest
    container:
      image: elixir:${{ matrix.elixir }}-alpine
      env:
        POSTGRES_HOST: postgres
        MIX_ENV: test

    services:
      postgres:
        image: postgres:9.6.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fsmx_test
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix ecto.migrate
      - run: mix test
